# Generated by Django 3.2.7 on 2021-10-13 08:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new', max_length=150, unique=True, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new', max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название склада')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('recipient', models.CharField(max_length=100, verbose_name='Получатель')),
                ('town', models.CharField(max_length=30, verbose_name='Город')),
                ('state', models.CharField(max_length=30, verbose_name='Штат')),
                ('postcode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Index must be entered in the format: XX XX XX', regex='^\\d{6}$')], verbose_name='Индекс')),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 996 999 999 999', regex='^(996)\\d{9}$')], verbose_name='Номер телефона')),
                ('image', models.ImageField(upload_to='news/warehouse', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='shop', verbose_name='Изображение')),
                ('logo', models.ImageField(upload_to='shop/icon', verbose_name='Логотип')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('link', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_shop', to='news.categoryshop')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='news')),
                ('description', models.TextField(max_length=500)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='news.category')),
            ],
        ),
    ]
