# Generated by Django 3.2.7 on 2021-10-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telegrambot',
            new_name='telegram',
        ),
    ]
