# Generated by Django 3.2.7 on 2021-10-16 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treck', models.CharField(default=False, max_length=50, unique=True, verbose_name='Трек номер')),
                ('recipient', models.CharField(max_length=100, verbose_name='Получатель')),
                ('parcels_name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('category', models.CharField(default=False, max_length=100, verbose_name='Категория')),
                ('amount', models.PositiveIntegerField(null=True, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена')),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Вес')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('web_site', models.URLField(verbose_name='Сайт')),
                ('comment', models.TextField(max_length=324, null=True, verbose_name='Комментарий')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('status', models.CharField(choices=[('InProcess', 'В процессе'), ('Completed', 'Обработан1'), ('Completed2', 'Обработан2'), ('Completed3', 'Обработан3'), ('Sort', 'Сортировка'), ('In Stock', 'На складе в KG1'), ('In Stock2', 'На складе в KG2'), ('In Stock3', 'На складе в KG3'), ('NotRegistred', 'Не зарегестрирован')], default='NotRegistred', max_length=100, verbose_name='Статус')),
                ('order', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
